//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerQuestionPaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnswerQuestionPaper()
        {
            this.TextAnswer = new HashSet<TextAnswer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AnswerQuestionID { get; set; }
        public Nullable<int> ExaminationPaperID { get; set; }
    
        public virtual AnswerQuestionBank AnswerQuestionBank { get; set; }
        public virtual ExaminationPaper ExaminationPaper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TextAnswer> TextAnswer { get; set; }
    }
}
