//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consult()
        {
            this.FollwingInfo = new HashSet<FollwingInfo>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TeacherName { get; set; }
        public Nullable<int> StuName { get; set; }
        public string Rmark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> ComDate { get; set; }
    
        public virtual ConsultTeacher ConsultTeacher { get; set; }
        public virtual StudentPutOnRecord StudentPutOnRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollwingInfo> FollwingInfo { get; set; }
    }
}
