//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormitoryMaintenance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DormitoryMaintenance()
        {
            this.Detailedmaintenance = new HashSet<Detailedmaintenance>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Key_name { get; set; }
        public Nullable<System.DateTime> Reentry { get; set; }
        public string Causesoffailure { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Dateofregistration { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detailedmaintenance> Detailedmaintenance { get; set; }
        public virtual DormInformation DormInformation { get; set; }
    }
}
