//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DormInformation()
        {
            this.Accdationinformation = new HashSet<Accdationinformation>();
            this.bedroom = new HashSet<bedroom>();
            this.DormitoryMaintenance = new HashSet<DormitoryMaintenance>();
            this.Dormitoryhygiene = new HashSet<Dormitoryhygiene>();
            this.DormitoryCharging = new HashSet<DormitoryCharging>();
            this.Montpowermission = new HashSet<Montpowermission>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> Types { get; set; }
        public Nullable<int> floor { get; set; }
        public Nullable<int> Roomtype { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accdationinformation> Accdationinformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bedroom> bedroom { get; set; }
        public virtual Dormitoryfloor Dormitoryfloor { get; set; }
        public virtual Roomtype Roomtype1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DormitoryMaintenance> DormitoryMaintenance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dormitoryhygiene> Dormitoryhygiene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DormitoryCharging> DormitoryCharging { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Montpowermission> Montpowermission { get; set; }
    }
}
