//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeesInfo()
        {
            this.ApplyForFullMember = new HashSet<ApplyForFullMember>();
            this.AttendanceInfo = new HashSet<AttendanceInfo>();
            this.bedroom = new HashSet<bedroom>();
            this.Break = new HashSet<Break>();
            this.ChannelStaff = new HashSet<ChannelStaff>();
            this.Check = new HashSet<Check>();
            this.ConsultTeacher = new HashSet<ConsultTeacher>();
            this.ConversationRecord = new HashSet<ConversationRecord>();
            this.Debit = new HashSet<Debit>();
            this.DimissionApply = new HashSet<DimissionApply>();
            this.EmpTransaction = new HashSet<EmpTransaction>();
            this.EmploymentStaff = new HashSet<EmploymentStaff>();
            this.EmplSalaryEmbody = new HashSet<EmplSalaryEmbody>();
            this.GoodsProvide = new HashSet<GoodsProvide>();
            this.Headmaster = new HashSet<Headmaster>();
            this.InStock = new HashSet<InStock>();
            this.InstructorList = new HashSet<InstructorList>();
            this.JobTransferApply = new HashSet<JobTransferApply>();
            this.LeaveRequest = new HashSet<LeaveRequest>();
            this.MarketChair = new HashSet<MarketChair>();
            this.MeritsCheck = new HashSet<MeritsCheck>();
            this.MonthlySalaryRecord = new HashSet<MonthlySalaryRecord>();
            this.NetClientRecord = new HashSet<NetClientRecord>();
            this.OvertimeRecord = new HashSet<OvertimeRecord>();
            this.PurchaseApply = new HashSet<PurchaseApply>();
            this.SalaryRaiseApply = new HashSet<SalaryRaiseApply>();
            this.SatisficingConfig = new HashSet<SatisficingConfig>();
            this.SocialSecurityDetail = new HashSet<SocialSecurityDetail>();
            this.StudentPutOnRecord = new HashSet<StudentPutOnRecord>();
            this.StudentPutOnRecord1 = new HashSet<StudentPutOnRecord>();
            this.TalentDemandPlan = new HashSet<TalentDemandPlan>();
            this.Teacher = new HashSet<Teacher>();
        }
    
        public string EmployeeId { get; set; }
        public Nullable<int> DDAppId { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string Nation { get; set; }
        public string Phone { get; set; }
        public string IdCardNum { get; set; }
        public Nullable<System.DateTime> ContractStartTime { get; set; }
        public Nullable<System.DateTime> ContractEndTime { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public Nullable<System.DateTime> ProbationEndTime { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Birthday { get; set; }
        public Nullable<System.DateTime> PositiveDate { get; set; }
        public string UrgentPhone { get; set; }
        public string DomicileAddress { get; set; }
        public string Address { get; set; }
        public string Education { get; set; }
        public Nullable<bool> MaritalStatus { get; set; }
        public Nullable<System.DateTime> IdCardIndate { get; set; }
        public string PoliticsStatus { get; set; }
        public string WorkExperience { get; set; }
        public Nullable<decimal> ProbationSalary { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<bool> WorkingState { get; set; }
        public string SSStartMonth { get; set; }
        public string BCNum { get; set; }
        public string Material { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplyForFullMember> ApplyForFullMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceInfo> AttendanceInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bedroom> bedroom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Break> Break { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelStaff> ChannelStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check> Check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultTeacher> ConsultTeacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConversationRecord> ConversationRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Debit> Debit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimissionApply> DimissionApply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpTransaction> EmpTransaction { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmploymentStaff> EmploymentStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmplSalaryEmbody> EmplSalaryEmbody { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsProvide> GoodsProvide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Headmaster> Headmaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InStock> InStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorList> InstructorList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobTransferApply> JobTransferApply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveRequest> LeaveRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketChair> MarketChair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeritsCheck> MeritsCheck { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlySalaryRecord> MonthlySalaryRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NetClientRecord> NetClientRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OvertimeRecord> OvertimeRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseApply> PurchaseApply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryRaiseApply> SalaryRaiseApply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisficingConfig> SatisficingConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialSecurityDetail> SocialSecurityDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPutOnRecord> StudentPutOnRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPutOnRecord> StudentPutOnRecord1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalentDemandPlan> TalentDemandPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teacher> Teacher { get; set; }
    }
}
