//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentStaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmploymentStaff()
        {
            this.EmpStaffAndStu = new HashSet<EmpStaffAndStu>();
            this.EnterpriseInfo = new HashSet<EnterpriseInfo>();
            this.SelfObtainRcored = new HashSet<SelfObtainRcored>();
            this.SimulatInterview = new HashSet<SimulatInterview>();
            this.SurveyRecords = new HashSet<SurveyRecords>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string EmployeesInfo_Id { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual EmpClass EmpClass { get; set; }
        public virtual EmployeesInfo EmployeesInfo { get; set; }
        public virtual EmploymentAreas EmploymentAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpStaffAndStu> EmpStaffAndStu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnterpriseInfo> EnterpriseInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfObtainRcored> SelfObtainRcored { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulatInterview> SimulatInterview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyRecords> SurveyRecords { get; set; }
    }
}
