//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnterpriseInfo()
        {
            this.CooperaEnterprises = new HashSet<CooperaEnterprises>();
            this.EntSpee = new HashSet<EntSpee>();
        }
    
        public int ID { get; set; }
        public string EntName { get; set; }
        public string EntAddress { get; set; }
        public string EntScale { get; set; }
        public string EntNature { get; set; }
        public string EntSalary { get; set; }
        public string EntWelfare { get; set; }
        public Nullable<System.DateTime> EntDate { get; set; }
        public Nullable<int> EmpStaffID { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CooperaEnterprises> CooperaEnterprises { get; set; }
        public virtual EmploymentStaff EmploymentStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntSpee> EntSpee { get; set; }
    }
}
