//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExaminationRoom()
        {
            this.ReadSweep = new HashSet<ReadSweep>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Classroom_Id { get; set; }
        public Nullable<int> Invigilator1 { get; set; }
        public Nullable<int> Invigilator2 { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Examination { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Examination Examination1 { get; set; }
        public virtual Headmaster Headmaster { get; set; }
        public virtual Headmaster Headmaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadSweep> ReadSweep { get; set; }
    }
}
