//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Examination()
        {
            this.CandidateInfo = new HashSet<CandidateInfo>();
            this.ExaminationRoom = new HashSet<ExaminationRoom>();
            this.ExamRoomDistributed = new HashSet<ExamRoomDistributed>();
            this.TestScore = new HashSet<TestScore>();
        }
    
        public int ID { get; set; }
        public string ExamNo { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<int> BaseID { get; set; }
        public Nullable<int> ExaminationPaper { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateInfo> CandidateInfo { get; set; }
        public virtual ExaminationPaper ExaminationPaper1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminationRoom> ExaminationRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamRoomDistributed> ExamRoomDistributed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestScore> TestScore { get; set; }
    }
}
