//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationPaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExaminationPaper()
        {
            this.AnswerQuestionPaper = new HashSet<AnswerQuestionPaper>();
            this.ChoiceQuestionPaper = new HashSet<ChoiceQuestionPaper>();
            this.Examination = new HashSet<Examination>();
            this.MachineTestQuestionPaper = new HashSet<MachineTestQuestionPaper>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<bool> IsUsing { get; set; }
        public Nullable<int> @int { get; set; }
        public Nullable<int> Type { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerQuestionPaper> AnswerQuestionPaper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChoiceQuestionPaper> ChoiceQuestionPaper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examination> Examination { get; set; }
        public virtual ExamType ExamType { get; set; }
        public virtual QuestionLevel QuestionLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineTestQuestionPaper> MachineTestQuestionPaper { get; set; }
    }
}
