//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveRequest()
        {
            this.CancelLeaveApply = new HashSet<CancelLeaveApply>();
        }
    
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<bool> 是否调休 { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public string LeaveReason { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelLeaveApply> CancelLeaveApply { get; set; }
        public virtual EmployeesInfo EmployeesInfo { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
