//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accdationinformation> Accdationinformation { get; set; }
        public virtual DbSet<AddCourse> AddCourse { get; set; }
        public virtual DbSet<AdmissArrangement> AdmissArrangement { get; set; }
        public virtual DbSet<AnswerQuestionBank> AnswerQuestionBank { get; set; }
        public virtual DbSet<AnswerQuestionPaper> AnswerQuestionPaper { get; set; }
        public virtual DbSet<ApplicationDropout> ApplicationDropout { get; set; }
        public virtual DbSet<ApplicationRepair> ApplicationRepair { get; set; }
        public virtual DbSet<ApplyForFullMember> ApplyForFullMember { get; set; }
        public virtual DbSet<Assmeetings> Assmeetings { get; set; }
        public virtual DbSet<AttendanceInfo> AttendanceInfo { get; set; }
        public virtual DbSet<Awardwinningtrainees> Awardwinningtrainees { get; set; }
        public virtual DbSet<BaseDataEnum> BaseDataEnum { get; set; }
        public virtual DbSet<Basicdat> Basicdat { get; set; }
        public virtual DbSet<bedroom> bedroom { get; set; }
        public virtual DbSet<BeOnDuty> BeOnDuty { get; set; }
        public virtual DbSet<BiddingRecord> BiddingRecord { get; set; }
        public virtual DbSet<BookInformation> BookInformation { get; set; }
        public virtual DbSet<Break> Break { get; set; }
        public virtual DbSet<CancelLeaveApply> CancelLeaveApply { get; set; }
        public virtual DbSet<CandidateInfo> CandidateInfo { get; set; }
        public virtual DbSet<CardRegistration> CardRegistration { get; set; }
        public virtual DbSet<CDInterview> CDInterview { get; set; }
        public virtual DbSet<ChannelStaff> ChannelStaff { get; set; }
        public virtual DbSet<ChannelYearPlan> ChannelYearPlan { get; set; }
        public virtual DbSet<Check> Check { get; set; }
        public virtual DbSet<CheckGoods> CheckGoods { get; set; }
        public virtual DbSet<ChoiceQuestionPaper> ChoiceQuestionPaper { get; set; }
        public virtual DbSet<ChooseAnswerSheet> ChooseAnswerSheet { get; set; }
        public virtual DbSet<Classactivities> Classactivities { get; set; }
        public virtual DbSet<ClassDynamics> ClassDynamics { get; set; }
        public virtual DbSet<ClassMeeting> ClassMeeting { get; set; }
        public virtual DbSet<ClassMembers> ClassMembers { get; set; }
        public virtual DbSet<Classroom> Classroom { get; set; }
        public virtual DbSet<Classroomequipment> Classroomequipment { get; set; }
        public virtual DbSet<ClassSchedule> ClassSchedule { get; set; }
        public virtual DbSet<ClassStudyGroup> ClassStudyGroup { get; set; }
        public virtual DbSet<ClassTeacher> ClassTeacher { get; set; }
        public virtual DbSet<ClassTeacherKeep> ClassTeacherKeep { get; set; }
        public virtual DbSet<Consult> Consult { get; set; }
        public virtual DbSet<ConsultTeacher> ConsultTeacher { get; set; }
        public virtual DbSet<ConversationRecord> ConversationRecord { get; set; }
        public virtual DbSet<ConvertCourse> ConvertCourse { get; set; }
        public virtual DbSet<CooperaEnterprises> CooperaEnterprises { get; set; }
        public virtual DbSet<Costlist> Costlist { get; set; }
        public virtual DbSet<CourseTime> CourseTime { get; set; }
        public virtual DbSet<CourseType> CourseType { get; set; }
        public virtual DbSet<Curriculum> Curriculum { get; set; }
        public virtual DbSet<Debit> Debit { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Detailedmaintenance> Detailedmaintenance { get; set; }
        public virtual DbSet<Detailedpayment> Detailedpayment { get; set; }
        public virtual DbSet<DetailedStudentIn> DetailedStudentIn { get; set; }
        public virtual DbSet<Detailsofacquisition> Detailsofacquisition { get; set; }
        public virtual DbSet<DetailsofCharges> DetailsofCharges { get; set; }
        public virtual DbSet<Detailsofconsignments> Detailsofconsignments { get; set; }
        public virtual DbSet<Dev_Project> Dev_Project { get; set; }
        public virtual DbSet<Dev_ProjectType> Dev_ProjectType { get; set; }
        public virtual DbSet<DimissionApply> DimissionApply { get; set; }
        public virtual DbSet<DisposalofDiscipline> DisposalofDiscipline { get; set; }
        public virtual DbSet<DormInformation> DormInformation { get; set; }
        public virtual DbSet<DormitoryCharging> DormitoryCharging { get; set; }
        public virtual DbSet<Dormitoryfloor> Dormitoryfloor { get; set; }
        public virtual DbSet<Dormitoryhygiene> Dormitoryhygiene { get; set; }
        public virtual DbSet<DormitoryMaintenance> DormitoryMaintenance { get; set; }
        public virtual DbSet<Electricitytarifftype> Electricitytarifftype { get; set; }
        public virtual DbSet<EmpClass> EmpClass { get; set; }
        public virtual DbSet<EmployedStudent> EmployedStudent { get; set; }
        public virtual DbSet<EmployeeArea> EmployeeArea { get; set; }
        public virtual DbSet<EmployeesInfo> EmployeesInfo { get; set; }
        public virtual DbSet<EmploymentAreas> EmploymentAreas { get; set; }
        public virtual DbSet<EmploymentStaff> EmploymentStaff { get; set; }
        public virtual DbSet<EmploySituation> EmploySituation { get; set; }
        public virtual DbSet<EmplSalaryEmbody> EmplSalaryEmbody { get; set; }
        public virtual DbSet<EmpQuarterClass> EmpQuarterClass { get; set; }
        public virtual DbSet<EmpStaffAndStu> EmpStaffAndStu { get; set; }
        public virtual DbSet<EmpTransaction> EmpTransaction { get; set; }
        public virtual DbSet<EnroExamination> EnroExamination { get; set; }
        public virtual DbSet<Enrollment> Enrollment { get; set; }
        public virtual DbSet<EnterpriseInfo> EnterpriseInfo { get; set; }
        public virtual DbSet<EntSpee> EntSpee { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Examination> Examination { get; set; }
        public virtual DbSet<ExaminationPaper> ExaminationPaper { get; set; }
        public virtual DbSet<ExaminationRoom> ExaminationRoom { get; set; }
        public virtual DbSet<ExamRoomDistributed> ExamRoomDistributed { get; set; }
        public virtual DbSet<ExamType> ExamType { get; set; }
        public virtual DbSet<Fiveroutines> Fiveroutines { get; set; }
        public virtual DbSet<FollwingInfo> FollwingInfo { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<GoodSkill> GoodSkill { get; set; }
        public virtual DbSet<GoodsProvide> GoodsProvide { get; set; }
        public virtual DbSet<GoodsType> GoodsType { get; set; }
        public virtual DbSet<Grand> Grand { get; set; }
        public virtual DbSet<GroupManagement> GroupManagement { get; set; }
        public virtual DbSet<Groupmembers> Groupmembers { get; set; }
        public virtual DbSet<HeadClass> HeadClass { get; set; }
        public virtual DbSet<Headmaster> Headmaster { get; set; }
        public virtual DbSet<HomeWorkFinishRate> HomeWorkFinishRate { get; set; }
        public virtual DbSet<InStock> InStock { get; set; }
        public virtual DbSet<InStockGoods> InStockGoods { get; set; }
        public virtual DbSet<InstructorList> InstructorList { get; set; }
        public virtual DbSet<Instructorsonduty> Instructorsonduty { get; set; }
        public virtual DbSet<InterviewRecordsof> InterviewRecordsof { get; set; }
        public virtual DbSet<InterviewStudents> InterviewStudents { get; set; }
        public virtual DbSet<IsGoodOrBad> IsGoodOrBad { get; set; }
        public virtual DbSet<JobTransferApply> JobTransferApply { get; set; }
        public virtual DbSet<LateEntryandExit> LateEntryandExit { get; set; }
        public virtual DbSet<LatesubmieCords> LatesubmieCords { get; set; }
        public virtual DbSet<LeaveRequest> LeaveRequest { get; set; }
        public virtual DbSet<LeaveType> LeaveType { get; set; }
        public virtual DbSet<MachineTestQuestionPaper> MachineTestQuestionPaper { get; set; }
        public virtual DbSet<MachTestQuesBank> MachTestQuesBank { get; set; }
        public virtual DbSet<MarketChair> MarketChair { get; set; }
        public virtual DbSet<MaterialPriceList> MaterialPriceList { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<MeritsCheck> MeritsCheck { get; set; }
        public virtual DbSet<MonthlySalaryRecord> MonthlySalaryRecord { get; set; }
        public virtual DbSet<Montpowermission> Montpowermission { get; set; }
        public virtual DbSet<MultipleChoiceQuestion> MultipleChoiceQuestion { get; set; }
        public virtual DbSet<NetClientRecord> NetClientRecord { get; set; }
        public virtual DbSet<NotreturningLate> NotreturningLate { get; set; }
        public virtual DbSet<NurseTeamInformation> NurseTeamInformation { get; set; }
        public virtual DbSet<NurseTeamonDuty> NurseTeamonDuty { get; set; }
        public virtual DbSet<NurseTeamPosition> NurseTeamPosition { get; set; }
        public virtual DbSet<Officebuildingonduty> Officebuildingonduty { get; set; }
        public virtual DbSet<Outbreaksindormitories> Outbreaksindormitories { get; set; }
        public virtual DbSet<OvertimeRecord> OvertimeRecord { get; set; }
        public virtual DbSet<ParticiParticipants> ParticiParticipants { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Pricedormitoryarticles> Pricedormitoryarticles { get; set; }
        public virtual DbSet<PrintGoodsApply> PrintGoodsApply { get; set; }
        public virtual DbSet<Professionala> Professionala { get; set; }
        public virtual DbSet<ProjectGroupMember> ProjectGroupMember { get; set; }
        public virtual DbSet<ProjectTasks> ProjectTasks { get; set; }
        public virtual DbSet<ProjectType> ProjectType { get; set; }
        public virtual DbSet<PurchaseApply> PurchaseApply { get; set; }
        public virtual DbSet<PurchaseType> PurchaseType { get; set; }
        public virtual DbSet<Quarter> Quarter { get; set; }
        public virtual DbSet<QuestionLevel> QuestionLevel { get; set; }
        public virtual DbSet<Rank> Rank { get; set; }
        public virtual DbSet<ReadSweep> ReadSweep { get; set; }
        public virtual DbSet<Reconcile> Reconcile { get; set; }
        public virtual DbSet<RecruitingDataSummary> RecruitingDataSummary { get; set; }
        public virtual DbSet<RecruitPhoneTrace> RecruitPhoneTrace { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<RemovalRecords> RemovalRecords { get; set; }
        public virtual DbSet<ReplenishmentRecord> ReplenishmentRecord { get; set; }
        public virtual DbSet<Restudy> Restudy { get; set; }
        public virtual DbSet<RoomPerformance> RoomPerformance { get; set; }
        public virtual DbSet<Roomtype> Roomtype { get; set; }
        public virtual DbSet<SalaryRaiseApply> SalaryRaiseApply { get; set; }
        public virtual DbSet<Satisfaction> Satisfaction { get; set; }
        public virtual DbSet<SatisficingConfig> SatisficingConfig { get; set; }
        public virtual DbSet<SatisficingItem> SatisficingItem { get; set; }
        public virtual DbSet<SatisficingResult> SatisficingResult { get; set; }
        public virtual DbSet<SatisficingResultDetail> SatisficingResultDetail { get; set; }
        public virtual DbSet<SatisficingType> SatisficingType { get; set; }
        public virtual DbSet<ScheduleForTrainees> ScheduleForTrainees { get; set; }
        public virtual DbSet<SchoolYearPlan> SchoolYearPlan { get; set; }
        public virtual DbSet<SelfObtainRcored> SelfObtainRcored { get; set; }
        public virtual DbSet<ShppingDetail> ShppingDetail { get; set; }
        public virtual DbSet<SimulatInterview> SimulatInterview { get; set; }
        public virtual DbSet<SocialSecProportion> SocialSecProportion { get; set; }
        public virtual DbSet<SocialSecurityDetail> SocialSecurityDetail { get; set; }
        public virtual DbSet<Specialty> Specialty { get; set; }
        public virtual DbSet<StageGrade> StageGrade { get; set; }
        public virtual DbSet<StockInfo> StockInfo { get; set; }
        public virtual DbSet<StrengthenClass> StrengthenClass { get; set; }
        public virtual DbSet<StrengthenStu> StrengthenStu { get; set; }
        public virtual DbSet<StuBookAcqRecords> StuBookAcqRecords { get; set; }
        public virtual DbSet<StudentAttendance> StudentAttendance { get; set; }
        public virtual DbSet<StudentAwardwinning> StudentAwardwinning { get; set; }
        public virtual DbSet<StudentFeeRecord> StudentFeeRecord { get; set; }
        public virtual DbSet<StudentFeeStandard> StudentFeeStandard { get; set; }
        public virtual DbSet<StudentInformation> StudentInformation { get; set; }
        public virtual DbSet<Studentmate> Studentmate { get; set; }
        public virtual DbSet<StudentPutOnRecord> StudentPutOnRecord { get; set; }
        public virtual DbSet<StudentUnionDepartment> StudentUnionDepartment { get; set; }
        public virtual DbSet<StudentUnionMembers> StudentUnionMembers { get; set; }
        public virtual DbSet<StudentUnionPosition> StudentUnionPosition { get; set; }
        public virtual DbSet<StudnetIntention> StudnetIntention { get; set; }
        public virtual DbSet<StuInfomationType> StuInfomationType { get; set; }
        public virtual DbSet<StuStatus> StuStatus { get; set; }
        public virtual DbSet<SubjectAchieve> SubjectAchieve { get; set; }
        public virtual DbSet<SurveyRecords> SurveyRecords { get; set; }
        public virtual DbSet<TalentDemandPlan> TalentDemandPlan { get; set; }
        public virtual DbSet<TeacheMitoryonduty> TeacheMitoryonduty { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<TeacherNight> TeacherNight { get; set; }
        public virtual DbSet<TecharOnstageBearing> TecharOnstageBearing { get; set; }
        public virtual DbSet<TestScore> TestScore { get; set; }
        public virtual DbSet<TextAnswer> TextAnswer { get; set; }
        public virtual DbSet<Timestamp> Timestamp { get; set; }
        public virtual DbSet<TotaleCharges> TotaleCharges { get; set; }
        public virtual DbSet<Transfer> Transfer { get; set; }
        public virtual DbSet<Trialapplication> Trialapplication { get; set; }
        public virtual DbSet<Undergra> Undergra { get; set; }
        public virtual DbSet<UnemployedStudent> UnemployedStudent { get; set; }
    }
}
