//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisficingConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SatisficingConfig()
        {
            this.SatisficingResult = new HashSet<SatisficingResult>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public string EmployeeId { get; set; }
        public string ClassNumber { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> IsPastDue { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        public virtual ClassSchedule ClassSchedule { get; set; }
        public virtual Curriculum Curriculum { get; set; }
        public virtual EmployeesInfo EmployeesInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisficingResult> SatisficingResult { get; set; }
    }
}
