//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisficingResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SatisficingResult()
        {
            this.SatisficingResultDetail = new HashSet<SatisficingResultDetail>();
        }
    
        public int ID { get; set; }
        public string Suggest { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<int> SatisficingConfig { get; set; }
        public string Answerer { get; set; }
    
        public virtual SatisficingConfig SatisficingConfig1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisficingResultDetail> SatisficingResultDetail { get; set; }
        public virtual StudentInformation StudentInformation { get; set; }
    }
}
