//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentInformation()
        {
            this.Accdationinformation = new HashSet<Accdationinformation>();
            this.ApplicationDropout = new HashSet<ApplicationDropout>();
            this.ApplicationRepair = new HashSet<ApplicationRepair>();
            this.Awardwinningtrainees = new HashSet<Awardwinningtrainees>();
            this.bedroom = new HashSet<bedroom>();
            this.CandidateInfo = new HashSet<CandidateInfo>();
            this.CardRegistration = new HashSet<CardRegistration>();
            this.ClassDynamics = new HashSet<ClassDynamics>();
            this.ClassMembers = new HashSet<ClassMembers>();
            this.ClassStudyGroup = new HashSet<ClassStudyGroup>();
            this.DetailedStudentIn = new HashSet<DetailedStudentIn>();
            this.DisposalofDiscipline = new HashSet<DisposalofDiscipline>();
            this.EnroExamination = new HashSet<EnroExamination>();
            this.Enrollment = new HashSet<Enrollment>();
            this.Groupmembers = new HashSet<Groupmembers>();
            this.HomeWorkFinishRate = new HashSet<HomeWorkFinishRate>();
            this.InterviewRecordsof = new HashSet<InterviewRecordsof>();
            this.InterviewStudents = new HashSet<InterviewStudents>();
            this.LateEntryandExit = new HashSet<LateEntryandExit>();
            this.LatesubmieCords = new HashSet<LatesubmieCords>();
            this.NurseTeamInformation = new HashSet<NurseTeamInformation>();
            this.ParticiParticipants = new HashSet<ParticiParticipants>();
            this.ProjectGroupMember = new HashSet<ProjectGroupMember>();
            this.ProjectTasks = new HashSet<ProjectTasks>();
            this.ReplenishmentRecord = new HashSet<ReplenishmentRecord>();
            this.Restudy = new HashSet<Restudy>();
            this.SatisficingResult = new HashSet<SatisficingResult>();
            this.ScheduleForTrainees = new HashSet<ScheduleForTrainees>();
            this.SelfObtainRcored = new HashSet<SelfObtainRcored>();
            this.SimulatInterview = new HashSet<SimulatInterview>();
            this.StrengthenStu = new HashSet<StrengthenStu>();
            this.StuBookAcqRecords = new HashSet<StuBookAcqRecords>();
            this.StudentAttendance = new HashSet<StudentAttendance>();
            this.StudentAwardwinning = new HashSet<StudentAwardwinning>();
            this.StudentFeeRecord = new HashSet<StudentFeeRecord>();
            this.Studentmate = new HashSet<Studentmate>();
            this.StudentUnionMembers = new HashSet<StudentUnionMembers>();
            this.StudnetIntention = new HashSet<StudnetIntention>();
            this.SurveyRecords = new HashSet<SurveyRecords>();
            this.Transfer = new HashSet<Transfer>();
            this.Trialapplication = new HashSet<Trialapplication>();
        }
    
        public string StudentNumber { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string identitydocument { get; set; }
        public string Telephone { get; set; }
        public string qq { get; set; }
        public string WeChat { get; set; }
        public string Picture { get; set; }
        public Nullable<int> State { get; set; }
        public string Hobby { get; set; }
        public string Family_address { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Nation { get; set; }
        public string Education { get; set; }
        public string Traine { get; set; }
        public string Password { get; set; }
        public Nullable<int> StudentPutOnRecord_Id { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> InsitDate { get; set; }
        public string Reack { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accdationinformation> Accdationinformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationDropout> ApplicationDropout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationRepair> ApplicationRepair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Awardwinningtrainees> Awardwinningtrainees { get; set; }
        public virtual Basicdat Basicdat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bedroom> bedroom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateInfo> CandidateInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardRegistration> CardRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassDynamics> ClassDynamics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassMembers> ClassMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassStudyGroup> ClassStudyGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailedStudentIn> DetailedStudentIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisposalofDiscipline> DisposalofDiscipline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnroExamination> EnroExamination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Groupmembers> Groupmembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeWorkFinishRate> HomeWorkFinishRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterviewRecordsof> InterviewRecordsof { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterviewStudents> InterviewStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LateEntryandExit> LateEntryandExit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LatesubmieCords> LatesubmieCords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NurseTeamInformation> NurseTeamInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticiParticipants> ParticiParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectGroupMember> ProjectGroupMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTasks> ProjectTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplenishmentRecord> ReplenishmentRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restudy> Restudy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisficingResult> SatisficingResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleForTrainees> ScheduleForTrainees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfObtainRcored> SelfObtainRcored { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulatInterview> SimulatInterview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StrengthenStu> StrengthenStu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StuBookAcqRecords> StuBookAcqRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttendance> StudentAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAwardwinning> StudentAwardwinning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentFeeRecord> StudentFeeRecord { get; set; }
        public virtual StudentPutOnRecord StudentPutOnRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Studentmate> Studentmate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentUnionMembers> StudentUnionMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudnetIntention> StudnetIntention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyRecords> SurveyRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer> Transfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trialapplication> Trialapplication { get; set; }
    }
}
