//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconValley.InformationSystem.Entity.MyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.AddCourse = new HashSet<AddCourse>();
            this.AnswerQuestionBank = new HashSet<AnswerQuestionBank>();
            this.ClassMeeting = new HashSet<ClassMeeting>();
            this.ClassTeacher = new HashSet<ClassTeacher>();
            this.ConvertCourse = new HashSet<ConvertCourse>();
            this.ConvertCourse1 = new HashSet<ConvertCourse>();
            this.GoodSkill = new HashSet<GoodSkill>();
            this.HomeWorkFinishRate = new HashSet<HomeWorkFinishRate>();
            this.MachTestQuesBank = new HashSet<MachTestQuesBank>();
            this.MultipleChoiceQuestion = new HashSet<MultipleChoiceQuestion>();
            this.ProjectTasks = new HashSet<ProjectTasks>();
            this.ReadSweep = new HashSet<ReadSweep>();
            this.Reconcile = new HashSet<Reconcile>();
            this.StrengthenClass = new HashSet<StrengthenClass>();
            this.TeacherNight = new HashSet<TeacherNight>();
            this.TecharOnstageBearing = new HashSet<TecharOnstageBearing>();
            this.TestScore = new HashSet<TestScore>();
        }
    
        public int TeacherID { get; set; }
        public string EmployeeId { get; set; }
        public string WorkExperience { get; set; }
        public string ProjectExperience { get; set; }
        public string TeachingExperience { get; set; }
        public string AttendClassStyle { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<int> MinimumCourseHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddCourse> AddCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerQuestionBank> AnswerQuestionBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassMeeting> ClassMeeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassTeacher> ClassTeacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConvertCourse> ConvertCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConvertCourse> ConvertCourse1 { get; set; }
        public virtual EmployeesInfo EmployeesInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodSkill> GoodSkill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeWorkFinishRate> HomeWorkFinishRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachTestQuesBank> MachTestQuesBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MultipleChoiceQuestion> MultipleChoiceQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTasks> ProjectTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadSweep> ReadSweep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reconcile> Reconcile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StrengthenClass> StrengthenClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherNight> TeacherNight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TecharOnstageBearing> TecharOnstageBearing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestScore> TestScore { get; set; }
    }
}
